const q = (pergunta, opcoes, respostaCorreta) => ({ pergunta, opcoes, respostaCorreta });

const bancos = {
    Matemática: [
        q('Se f(x)=2x²-3x+1, qual é f(2)?', ['1', '3', '5', '7'], 2),
        q('A soma dos ângulos internos de um hexágono é:', ['540°', '720°', '900°', '1080°'], 1),
        q('Qual é a razão entre 18 e 24 simplificada?', ['2/3', '3/4', '4/5', '5/6'], 1),
        q('Um produto de R$ 200 recebe desconto de 15%. Qual o preço final?', ['R$ 160', 'R$ 170', 'R$ 175', 'R$ 185'], 1),
        q('Qual é a solução positiva de x²-9=0?', ['1', '3', '6', '9'], 1),
        q('A média de 8, 12, 15 e 5 é:', ['8', '9', '10', '11'], 2),
        q('Se 3/5 de um número é 24, o número é:', ['30', '36', '40', '45'], 2),
        q('Qual é a área de um círculo de raio 3, usando π=3,14?', ['18,84', '28,26', '37,68', '56,52'], 1),
        q('Na sequência 4, 9, 14, 19, o próximo termo é:', ['22', '23', '24', '25'], 2),
        q('Quanto vale 2³·2⁴?', ['32', '64', '128', '256'], 2)
    ],
    Português: [
        q('Em “Embora estudasse, não foi aprovado”, “embora” introduz uma oração:', ['causal', 'concessiva', 'condicional', 'consecutiva'], 1),
        q('A palavra “inconstitucional” é formada principalmente por:', ['derivação regressiva', 'composição', 'derivação prefixal e sufixal', 'abreviação'], 2),
        q('Em “Vendem-se casas”, o “se” é:', ['pronome reflexivo', 'índice de indeterminação', 'partícula apassivadora', 'conjunção'], 2),
        q('A concordância correta é:', ['Fazem dois anos', 'Houveram problemas', 'Faz dois anos', 'Existe muitas dúvidas'], 2),
        q('Em “O livro que comprei sumiu”, “que” exerce função de:', ['sujeito', 'objeto direto', 'adjunto adverbial', 'predicativo'], 1),
        q('A regência correta é:', ['Assisti o filme', 'Prefiro mais café', 'Obedeço às regras', 'Cheguei no local'], 2),
        q('“A cidade dormia” apresenta:', ['metonímia', 'personificação', 'antítese', 'eufemismo'], 1),
        q('A oração “quando terminou a aula” indica circunstância de:', ['tempo', 'causa', 'finalidade', 'concessão'], 0),
        q('Em “É necessário que todos participem”, a oração destacada é:', ['substantiva subjetiva', 'adjetiva restritiva', 'adverbial causal', 'substantiva objetiva'], 0),
        q('A colocação pronominal em “Não me conte isso” é:', ['ênclise', 'mesóclise', 'próclise', 'apóclise'], 2)
    ],
    História: [
        q('A Revolução Francesa começou em 1789 sob forte influência do:', ['absolutismo', 'Iluminismo', 'mercantilismo', 'feudalismo'], 1),
        q('A Era Vargas iniciou-se com a:', ['Revolução de 1930', 'Constituição de 1824', 'Proclamação da República', 'Guerra de Canudos'], 0),
        q('O AI-5, decretado em 1968, marcou:', ['abertura política', 'aumento da repressão da ditadura', 'fim do Estado Novo', 'início da República'], 1),
        q('A política do café com leite alternava o poder entre São Paulo e:', ['Bahia', 'Minas Gerais', 'Pernambuco', 'Rio Grande do Sul'], 1),
        q('A Conferência de Berlim relaciona-se principalmente à:', ['descolonização da Ásia', 'partilha da África', 'criação da ONU', 'Revolução Russa'], 1),
        q('A Guerra Fria foi marcada pela disputa entre:', ['EUA e URSS', 'França e Inglaterra', 'China e Japão', 'Brasil e Argentina'], 0),
        q('A Constituição brasileira de 1988 ficou conhecida como:', ['Constituição Cidadã', 'Carta Imperial', 'Constituição Militar', 'Carta do Estado Novo'], 0),
        q('O mercantilismo valorizava, entre outros fatores:', ['metalismo e balança comercial favorável', 'fim dos monopólios', 'economia de subsistência', 'igualdade agrária'], 0),
        q('A Inconfidência Mineira foi influenciada pela independência dos:', ['Estados Unidos', 'países africanos', 'reinos germânicos', 'impérios asiáticos'], 0),
        q('O Tratado de Tordesilhas dividiu áreas ultramarinas entre:', ['Portugal e Espanha', 'França e Inglaterra', 'Holanda e França', 'Espanha e Itália'], 0)
    ],
    Geografia: [
        q('O fenômeno El Niño corresponde ao aquecimento anormal das águas do:', ['Atlântico Norte', 'Pacífico Equatorial', 'Índico Sul', 'Mediterrâneo'], 1),
        q('A projeção de Mercator é criticada por distorcer principalmente:', ['áreas em altas latitudes', 'fusos horários', 'altitudes locais', 'fronteiras políticas'], 0),
        q('A maior bacia hidrográfica brasileira é a:', ['do Paraná', 'Amazônica', 'do São Francisco', 'do Tocantins-Araguaia'], 1),
        q('O processo de urbanização sem planejamento pode intensificar:', ['ilhas de calor e enchentes', 'terremotos', 'marés', 'auroras'], 0),
        q('A latitude mede a distância em relação:', ['ao Meridiano de Greenwich', 'à Linha do Equador', 'aos trópicos apenas', 'aos polos apenas'], 1),
        q('A transição demográfica tende a ocorrer com:', ['queda da mortalidade e depois da natalidade', 'aumento permanente da natalidade', 'fim da urbanização', 'crescimento da mortalidade infantil'], 0),
        q('A desertificação está associada à degradação de terras em:', ['áreas áridas e semiáridas', 'zonas polares apenas', 'florestas úmidas intactas', 'oceanos profundos'], 0),
        q('A globalização intensifica principalmente:', ['fluxos de mercadorias, capitais e informações', 'isolamento econômico', 'fim das redes digitais', 'redução dos transportes'], 0),
        q('O aquífero é uma formação que armazena:', ['água subterrânea', 'lava', 'petróleo obrigatoriamente', 'gelo atmosférico'], 0),
        q('A latitude influencia diretamente a variação de:', ['incidência solar', 'composição do núcleo', 'salinidade de todo rio', 'rotação da Lua'], 0)
    ],
    Ciências: [
        q('A seleção natural favorece características que:', ['aumentam a sobrevivência e reprodução', 'surgem sempre por necessidade', 'impedem mutações', 'são adquiridas por treino'], 0),
        q('A segunda lei de Newton é expressa por:', ['E=mc²', 'F=m·a', 'V=R·i', 'P=U·i'], 1),
        q('A fotossíntese utiliza dióxido de carbono e água para produzir:', ['glicose e oxigênio', 'proteínas e nitrogênio', 'gordura e metano', 'álcool e ozônio'], 0),
        q('O pH abaixo de 7 indica uma solução:', ['básica', 'neutra', 'ácida', 'salina'], 2),
        q('A corrente elétrica é medida em:', ['volts', 'amperes', 'ohms', 'watts'], 1),
        q('O DNA apresenta como função principal:', ['armazenar informação genética', 'produzir energia diretamente', 'digerir lipídios', 'transportar oxigênio'], 0),
        q('A pressão atmosférica tende a diminuir quando:', ['a altitude aumenta', 'a altitude diminui', 'a umidade zera', 'a latitude aumenta sempre'], 0),
        q('A transformação de líquido em vapor é:', ['condensação', 'vaporização', 'fusão', 'sublimação'], 1),
        q('Em uma cadeia alimentar, os produtores são geralmente:', ['fungos', 'plantas e algas', 'carnívoros', 'decompositores'], 1),
        q('A unidade de energia no SI é o:', ['newton', 'joule', 'pascal', 'watt'], 1)
    ],
    Biologia: [
        q('A meiose produz células com:', ['o dobro de cromossomos', 'metade dos cromossomos', 'nenhum cromossomo', 'cromossomos idênticos sempre'], 1),
        q('As enzimas atuam principalmente como:', ['catalisadores biológicos', 'fontes de DNA', 'hormônios sexuais', 'anticorpos estruturais'], 0),
        q('A organela responsável pela respiração celular é a:', ['mitocôndria', 'ribossomo', 'lisossomo', 'cloroplasto'], 0),
        q('O tecido que conduz impulsos nervosos é o:', ['epitelial', 'conjuntivo', 'nervoso', 'muscular'], 2),
        q('A relação em que ambas as espécies se beneficiam é:', ['parasitismo', 'mutualismo', 'amensalismo', 'predação'], 1),
        q('A insulina reduz a glicose no sangue ao favorecer sua:', ['excreção imediata', 'entrada nas células', 'conversão em oxigênio', 'produção no fígado'], 1),
        q('Na respiração humana, as trocas gasosas ocorrem nos:', ['brônquios', 'alvéolos', 'bronquíolos apenas', 'diafragma'], 1),
        q('O RNA mensageiro participa da:', ['síntese de proteínas', 'duplicação de ossos', 'digestão extracelular', 'produção de bile'], 0),
        q('A imunidade adquirida por vacina é geralmente:', ['ativa e artificial', 'passiva e natural', 'inata', 'passiva e artificial'], 0),
        q('A sucessão ecológica descreve:', ['mudanças graduais em uma comunidade', 'migração diária de animais', 'divisão celular', 'formação de rochas'], 0)
    ],
    Física: [
        q('Um corpo em movimento retilíneo uniforme possui aceleração:', ['constante e positiva', 'nula', 'variável', 'igual à velocidade'], 1),
        q('A resistência elétrica é medida em:', ['ampere', 'volt', 'ohm', 'joule'], 2),
        q('A energia potencial gravitacional depende da altura e da:', ['massa', 'temperatura', 'carga elétrica', 'frequência'], 0),
        q('Quando a luz passa do ar para a água, sua velocidade:', ['aumenta', 'diminui', 'fica infinita', 'não se altera sempre'], 1),
        q('O trabalho de uma força é nulo quando força e deslocamento são:', ['paralelos', 'perpendiculares', 'iguais', 'opostos sempre'], 1),
        q('A frequência de uma onda é medida em:', ['hertz', 'newton', 'pascal', 'tesla'], 0),
        q('A pressão é definida como força dividida pela:', ['massa', 'área', 'velocidade', 'energia'], 1),
        q('Em um circuito em série, a corrente é:', ['a mesma em todos os componentes', 'nula no resistor', 'maior no primeiro componente', 'igual à tensão'], 0),
        q('O impulso de uma força está relacionado à variação da:', ['quantidade de movimento', 'temperatura', 'densidade', 'potência luminosa'], 0),
        q('A terceira lei de Newton trata de forças:', ['sem relação', 'de ação e reação', 'sempre paralelas', 'apenas gravitacionais'], 1)
    ],
    Química: [
        q('Uma ligação iônica ocorre tipicamente entre:', ['dois ametais', 'metal e ametal', 'metal e não metal', 'gases nobres'], 2),
        q('O número de prótons de um átomo define seu:', ['número atômico', 'número de massa', 'nível energético', 'isótopo'], 0),
        q('Uma reação que libera calor é:', ['endotérmica', 'exotérmica', 'isotérmica', 'nuclear sempre'], 1),
        q('A molaridade é expressa em:', ['mol/L', 'g/L²', 'L/mol²', 'kg/m³ apenas'], 0),
        q('Catalisadores aumentam a velocidade da reação ao:', ['reduzir a energia de ativação', 'aumentar a massa dos produtos', 'serem consumidos', 'mudar os elementos'], 0),
        q('Isótopos possuem o mesmo número de prótons e diferentes números de:', ['elétrons apenas', 'nêutrons', 'moléculas', 'ligações'], 1),
        q('Uma solução de pH 3 é mais ácida que uma de pH:', ['2', '1', '4', '3'], 2),
        q('A oxidação corresponde à:', ['perda de elétrons', 'ganho de elétrons', 'perda de prótons sempre', 'formação de nêutrons'], 0),
        q('A função orgânica que contém o grupo -OH ligado a carbono saturado é:', ['álcool', 'aldeído', 'cetona', 'éster'], 0),
        q('Na tabela periódica, elementos do mesmo grupo tendem a ter:', ['propriedades químicas semelhantes', 'mesma massa', 'mesmo número de nêutrons', 'mesmo período'], 0)
    ],
    Inglês: [
        q('Choose the correct option: “If I had known, I ___ earlier.”', ['will leave', 'would have left', 'leave', 'am leaving'], 1),
        q('The word “although” expresses:', ['contrast', 'cause', 'purpose', 'addition'], 0),
        q('Complete: “She has lived here ___ 2019.”', ['for', 'since', 'during', 'by'], 1),
        q('Which sentence is in the passive voice?', ['They built the bridge.', 'The bridge was built.', 'They are building it.', 'Build the bridge.'], 1),
        q('“Reliable” is closest in meaning to:', ['trustworthy', 'expensive', 'temporary', 'dangerous'], 0),
        q('Complete: “I am interested ___ science.”', ['on', 'at', 'in', 'by'], 2),
        q('The plural of “analysis” is:', ['analysises', 'analyses', 'analysis', 'analysies'], 1),
        q('Choose the correct reported speech: He said, “I am tired.”', ['He said he is tired.', 'He said he was tired.', 'He says he tired.', 'He said I was tired.'], 1),
        q('“Despite” is normally followed by:', ['a noun or gerund', 'a bare infinitive only', 'a question word', 'a modal verb'], 0),
        q('Complete: “Neither the teacher nor the students ___ late.”', ['was', 'is', 'were', 'be'], 2)
    ],
    Literatura: [
        q('O Realismo brasileiro caracteriza-se pela:', ['idealização amorosa', 'análise crítica da sociedade', 'valorização do medievalismo', 'evasão absoluta'], 1),
        q('Em “Memórias Póstumas de Brás Cubas”, o narrador é:', ['onisciente neutro', 'um defunto autor', 'um narrador testemunha', 'um narrador infantil'], 1),
        q('O Modernismo brasileiro teve como marco inicial:', ['Semana de 1922', 'Inconfidência Mineira', 'Arcadismo', 'Romantismo'], 0),
        q('A intertextualidade ocorre quando um texto:', ['dialoga com outro texto', 'não possui autor', 'usa somente números', 'abandona a linguagem'], 0),
        q('O foco narrativo em primeira pessoa limita-se geralmente:', ['ao conhecimento do narrador', 'à visão do leitor', 'ao futuro da história', 'à descrição científica'], 0),
        q('O verso sem métrica fixa e sem rima obrigatória é chamado:', ['verso livre', 'redondilha', 'soneto', 'alexandrino'], 0),
        q('O Naturalismo enfatiza explicações ligadas ao:', ['determinismo e meio', 'idealismo platônico', 'heroísmo medieval', 'sobrenatural religioso'], 0),
        q('A ironia produz sentido ao:', ['afirmar algo que sugere o contrário', 'repetir literalmente', 'eliminar ambiguidades', 'usar apenas fatos'], 0),
        q('A obra “O Cortiço”, de Aluísio Azevedo, pertence ao:', ['Naturalismo', 'Trovadorismo', 'Arcadismo', 'Simbolismo'], 0),
        q('A função poética da linguagem destaca:', ['a forma da mensagem', 'apenas o referente', 'o canal físico', 'a ordem do emissor'], 0)
    ],
    Tecnologia: [
        q('Em segurança digital, phishing é:', ['fraude para obter dados por engenharia social', 'backup automático', 'criptografia de disco', 'atualização de sistema'], 0),
        q('Uma API é usada para:', ['permitir comunicação entre sistemas', 'aumentar a memória física', 'resfriar o processador', 'substituir o sistema operacional'], 0),
        q('Em bancos de dados, uma chave primária deve:', ['identificar registros de forma única', 'repetir valores', 'armazenar imagens apenas', 'ser sempre textual'], 0),
        q('HTTPS protege a comunicação principalmente com:', ['TLS', 'FTP', 'CSS', 'DNS puro'], 0),
        q('O algoritmo de busca binária exige uma lista:', ['ordenada', 'aleatória', 'vazia', 'duplicada obrigatoriamente'], 0),
        q('Machine learning supervisionado utiliza:', ['dados rotulados', 'nenhum dado', 'somente regras fixas', 'apenas imagens sintéticas'], 0),
        q('O princípio da menor permissão recomenda:', ['conceder apenas acessos necessários', 'dar acesso total', 'compartilhar senhas', 'desativar logs'], 0),
        q('Git é principalmente um sistema de:', ['controle de versão', 'edição de imagens', 'gerenciamento de memória', 'transmissão de vídeo'], 0),
        q('Em HTML, o atributo alt de uma imagem favorece:', ['acessibilidade e descrição alternativa', 'criptografia', 'compressão obrigatória', 'execução de JavaScript'], 0),
        q('Uma transação ACID deve preservar principalmente:', ['consistência dos dados', 'cores da interface', 'velocidade da rede', 'resolução da tela'], 0)
    ],
    Artes: [
        q('O Barroco é marcado frequentemente por:', ['contrastes e conflito entre material e espiritual', 'simplicidade geométrica absoluta', 'ausência de religiosidade', 'rejeição do drama'], 0),
        q('A perspectiva linear cria profundidade por meio de:', ['linhas convergentes', 'cores fluorescentes apenas', 'textura sonora', 'simetria obrigatória'], 0),
        q('O Impressionismo valorizou:', ['luz e percepção momentânea', 'temas exclusivamente mitológicos', 'contornos rígidos', 'monocromia'], 0),
        q('A instalação artística geralmente:', ['ocupa e transforma um espaço', 'existe só em papel', 'é sempre uma escultura clássica', 'não envolve o público'], 0),
        q('A composição visual organiza:', ['elementos como forma, cor e equilíbrio', 'apenas o título', 'somente o material', 'o preço da obra'], 0),
        q('A arte abstrata não depende necessariamente de:', ['representação figurativa reconhecível', 'cor', 'forma', 'composição'], 0),
        q('O cubismo explorou a representação de objetos por:', ['múltiplos pontos de vista', 'uma única perspectiva fotográfica', 'ausência de geometria', 'paisagens realistas apenas'], 0),
        q('O ritmo musical resulta da organização de:', ['durações e pulsações', 'cores e volumes', 'texturas e tintas', 'perspectivas'], 0),
        q('A xilogravura utiliza como matriz principalmente:', ['madeira', 'vidro líquido', 'tecido', 'argila sem secar'], 0),
        q('A arte pública é produzida ou apresentada:', ['em espaços de acesso coletivo', 'somente em coleções privadas', 'apenas em livros', 'sem relação com o ambiente'], 0)
    ],
    Filosofia: [
        q('Para Platão, o conhecimento verdadeiro relaciona-se ao mundo:', ['das ideias', 'das aparências sensíveis apenas', 'das opiniões políticas', 'dos mitos populares'], 0),
        q('O imperativo categórico é associado a:', ['Kant', 'Marx', 'Aristóteles', 'Epicuro'], 0),
        q('Para Aristóteles, a virtude está relacionada ao:', ['justo meio', 'excesso constante', 'abandono da razão', 'prazer imediato'], 0),
        q('O existencialismo enfatiza a:', ['liberdade e responsabilidade do indivíduo', 'predestinação absoluta', 'negação da escolha', 'superioridade da técnica'], 0),
        q('O método socrático baseia-se principalmente em:', ['perguntas e diálogo crítico', 'memorização dogmática', 'experimentos químicos', 'silêncio contemplativo'], 0),
        q('Para Hobbes, o Estado surge para conter:', ['o conflito no estado de natureza', 'a matemática', 'a produção artística', 'a observação científica'], 0),
        q('O empirismo considera a experiência uma fonte central de:', ['conhecimento', 'autoridade política', 'beleza artística', 'moral religiosa apenas'], 0),
        q('A falácia ad hominem ataca:', ['a pessoa em vez do argumento', 'a conclusão matemática', 'a definição de termos', 'a evidência relevante'], 0),
        q('Para Nietzsche, a crítica à moral tradicional envolve a ideia de:', ['transvaloração dos valores', 'retorno ao feudalismo', 'negação da criação', 'imitação platônica'], 0),
        q('A ética consequencialista avalia ações sobretudo por:', ['seus resultados', 'a intenção apenas', 'a tradição', 'a aparência'], 0)
    ],
    'Educação Financeira': [
        q('Juros compostos incidem sobre:', ['capital e juros acumulados', 'capital inicial apenas', 'taxas sem capital', 'inflação somente'], 0),
        q('Diversificação reduz principalmente:', ['risco concentrado', 'renda garantida', 'necessidade de planejamento', 'liquidez de todos os ativos'], 0),
        q('O custo de oportunidade representa:', ['o benefício da alternativa abandonada', 'a taxa de inflação', 'o imposto fixo', 'o saldo bancário'], 0),
        q('Liquidez de um investimento indica:', ['facilidade de convertê-lo em dinheiro', 'risco de perda zero', 'rentabilidade máxima', 'prazo infinito'], 0),
        q('Inflação elevada reduz o poder de compra quando:', ['preços sobem mais que a renda', 'preços caem sempre', 'renda aumenta mais que preços', 'não há moeda'], 0),
        q('Uma reserva de emergência deve priorizar:', ['liquidez e baixo risco', 'especulação', 'prazo muito longo', 'concentração em um ativo'], 0),
        q('Valor presente líquido considera:', ['fluxos futuros descontados', 'somente o preço inicial', 'apenas impostos', 'o saldo sem prazo'], 0),
        q('A taxa de juros real corresponde aproximadamente à taxa nominal menos:', ['inflação', 'renda', 'liquidez', 'patrimônio'], 0),
        q('Endividamento sustentável exige que parcelas:', ['caibam no orçamento', 'superem a renda', 'sejam ignoradas', 'não tenham prazo'], 0),
        q('Um orçamento base zero começa:', ['justificando cada despesa', 'repetindo o gasto anterior', 'eliminando toda renda', 'investindo sem meta'], 0)
    ],
    Saúde: [
        q('A resistência bacteriana é favorecida principalmente pelo:', ['uso inadequado de antibióticos', 'uso de vacinas', 'consumo de água', 'sono regular'], 0),
        q('O sistema imunológico adaptativo possui:', ['memória imunológica', 'apenas barreiras físicas', 'função exclusiva respiratória', 'nenhum anticorpo'], 0),
        q('A hipertensão é um fator de risco para:', ['doenças cardiovasculares', 'miopia apenas', 'fraturas sempre', 'alergia alimentar'], 0),
        q('Fibras alimentares auxiliam principalmente o:', ['trânsito intestinal', 'transporte de oxigênio', 'crescimento ósseo direto', 'controle da audição'], 0),
        q('O sono adequado favorece:', ['memória e recuperação', 'desidratação', 'perda permanente de atenção', 'aumento da inflamação sempre'], 0),
        q('A vacinação protege a população por estimular:', ['resposta imune específica', 'produção de antibiótico no ambiente', 'aumento da temperatura', 'destruição de todas as bactérias'], 0),
        q('Uma dieta equilibrada deve considerar:', ['variedade e adequação nutricional', 'exclusão de todos os carboidratos', 'apenas suplementos', 'jejum permanente'], 0),
        q('A atividade física regular pode melhorar:', ['capacidade cardiorrespiratória', 'todas as doenças sem exceção', 'necessidade de cigarro', 'desidratação crônica'], 0),
        q('Saúde mental envolve também:', ['relações e contexto social', 'ausência total de emoções', 'isolamento obrigatório', 'apenas força física'], 0),
        q('Higienização das mãos reduz:', ['transmissão de microrganismos', 'necessidade de vacinação', 'todas as doenças genéticas', 'poluição atmosférica'], 0)
    ],
    'Meio Ambiente': [
        q('A eutrofização de rios pode resultar do excesso de:', ['nutrientes', 'oxigênio puro', 'areia limpa', 'luz solar'], 0),
        q('A biomagnificação aumenta a concentração de poluentes:', ['ao longo da cadeia alimentar', 'apenas na água da chuva', 'no solo sem organismos', 'em produtores sempre menos'], 0),
        q('O desmatamento pode alterar o ciclo:', ['hidrológico', 'das marés lunares', 'das rochas', 'do campo magnético apenas'], 0),
        q('A economia circular busca:', ['reduzir desperdício e manter materiais em uso', 'aumentar descarte', 'eliminar reciclagem', 'usar recursos uma única vez'], 0),
        q('O gás de efeito estufa mais associado à queima de combustíveis é:', ['CO₂', 'O₂', 'N₂', 'He'], 0),
        q('Corredores ecológicos favorecem:', ['conectividade entre habitats', 'isolamento de espécies', 'urbanização de rios', 'redução da biodiversidade'], 0),
        q('A mata ciliar contribui para:', ['proteger margens e reduzir erosão', 'aumentar assoreamento', 'secar rios', 'eliminar nascentes'], 0),
        q('Pegada ecológica estima:', ['pressão do consumo sobre recursos naturais', 'temperatura do ar', 'idade de uma floresta', 'velocidade de rios'], 0),
        q('Espécies invasoras podem causar:', ['desequilíbrio ecológico', 'aumento garantido da biodiversidade', 'fim da competição', 'restauração automática'], 0),
        q('A energia eólica é considerada renovável porque usa:', ['movimento do vento', 'carvão', 'petróleo', 'urânio finito'], 0)
    ],
    'Conhecimentos Gerais': [
        q('A sede da Organização Mundial da Saúde fica em:', ['Genebra', 'Paris', 'Roma', 'Bruxelas'], 0),
        q('O elemento químico de símbolo Fe é:', ['ferro', 'flúor', 'frâncio', 'fósforo'], 0),
        q('A camada da atmosfera onde ocorre a maior parte do clima é a:', ['troposfera', 'estratosfera', 'mesosfera', 'exosfera'], 0),
        q('O maior planeta do Sistema Solar é:', ['Júpiter', 'Saturno', 'Terra', 'Netuno'], 0),
        q('A moeda oficial do Japão é o:', ['iene', 'won', 'yuan', 'baht'], 0),
        q('A Declaração Universal dos Direitos Humanos foi adotada pela ONU em:', ['1948', '1918', '1968', '1988'], 0),
        q('O número romano XL representa:', ['40', '60', '90', '110'], 0),
        q('A fotossíntese ocorre principalmente nos:', ['cloroplastos', 'núcleos', 'lisossomos', 'centríolos'], 0),
        q('O oceano que banha a costa leste do Brasil é o:', ['Atlântico', 'Pacífico', 'Índico', 'Ártico'], 0),
        q('A unidade básica de informação digital é o:', ['bit', 'byte', 'pixel', 'hertz'], 0)
    ],
    Raciocínio: [
        q('Se todos A são B e nenhum B é C, então:', ['nenhum A é C', 'todo C é A', 'algum A é C', 'todo B é A'], 0),
        q('Complete: 2, 6, 12, 20, 30, ...', ['36', '40', '42', '44'], 2),
        q('Se hoje é terça-feira, que dia será daqui a 45 dias?', ['quinta-feira', 'sexta-feira', 'sábado', 'domingo'], 1),
        q('Um cubo possui quantas arestas?', ['8', '10', '12', '14'], 2),
        q('A negação de “todos estudaram” é:', ['ninguém estudou', 'pelo menos um não estudou', 'todos não estudaram', 'alguns estudaram'], 1),
        q('Se 5 máquinas fazem 5 peças em 5 minutos, 1 máquina faz 1 peça em:', ['1 minuto', '5 minutos', '10 minutos', '25 minutos'], 1),
        q('Qual número completa: 1, 1, 2, 3, 5, 8, ...', ['11', '12', '13', '15'], 2),
        q('Em uma fila, Ana está antes de Bia e depois de Caio. Quem está no meio?', ['Ana', 'Bia', 'Caio', 'não é possível saber'], 0),
        q('Se uma proposição é verdadeira, sua negação é:', ['verdadeira', 'falsa', 'indeterminada sempre', 'ambas'], 1),
        q('Um relógio adianta 5 minutos por hora. Em 6 horas, adiantará:', ['11 min', '25 min', '30 min', '35 min'], 2)
    ],
    'Revisão Escolar': [
        q('Na fotossíntese, a clorofila capta principalmente:', ['energia luminosa', 'energia sonora', 'nitrogênio atmosférico', 'calor geotérmico'], 0),
        q('A Revolução Industrial começou na:', ['Inglaterra', 'Rússia', 'Espanha', 'Grécia'], 0),
        q('A oração “porque choveu” normalmente expressa:', ['causa', 'concessão', 'condição', 'finalidade'], 0),
        q('A unidade de medida de potência é:', ['watt', 'joule', 'newton', 'pascal'], 0),
        q('O continente com maior população é:', ['Ásia', 'África', 'Europa', 'América'], 0),
        q('A Constituição é a lei:', ['fundamental de um Estado', 'exclusiva do município', 'apenas eleitoral', 'sem valor jurídico'], 0),
        q('A mitose produz células:', ['geneticamente semelhantes', 'com metade dos cromossomos sempre', 'sem núcleo', 'exclusivamente sexuais'], 0),
        q('A escala de um mapa relaciona:', ['distância representada e real', 'temperatura e altitude', 'população e renda', 'latitude e clima apenas'], 0),
        q('A água é uma molécula formada por:', ['dois hidrogênios e um oxigênio', 'dois oxigênios e um carbono', 'um hidrogênio e dois carbonos', 'um só elemento'], 0),
        q('A média aritmética soma os valores e divide pela:', ['quantidade de valores', 'maior valor', 'menor valor', 'diferença entre eles'], 0)
    ],
    'Cultura e Sociedade': [
        q('Cultura é aprendida e compartilhada por meio de:', ['interações sociais', 'herança genética apenas', 'isolamento absoluto', 'fenômenos naturais'], 0),
        q('Etnocentrismo ocorre quando alguém:', ['julga outra cultura pelos padrões da própria', 'valoriza a diversidade', 'abandona sua língua', 'estuda economia'], 0),
        q('Cidadania envolve:', ['direitos e deveres na sociedade', 'apenas consumo', 'isolamento político', 'ausência de participação'], 0),
        q('A mobilidade social representa:', ['mudança de posição na estrutura social', 'migração de animais', 'troca de moeda', 'variação climática'], 0),
        q('Preconceito é uma atitude baseada em:', ['julgamento prévio', 'análise completa', 'evidência científica sempre', 'neutralidade absoluta'], 0),
        q('Instituições sociais organizam:', ['práticas e relações coletivas', 'somente jogos', 'apenas fenômenos físicos', 'o clima'], 0),
        q('A socialização primária ocorre principalmente:', ['na família e primeiros grupos', 'no mercado financeiro', 'em guerras', 'na vida adulta apenas'], 0),
        q('Democracia participativa valoriza:', ['participação popular nas decisões', 'poder hereditário', 'censura total', 'ausência de eleições'], 0),
        q('Desigualdade social refere-se à distribuição desigual de:', ['recursos e oportunidades', 'apenas opiniões', 'estações do ano', 'línguas naturais'], 0),
        q('Patrimônio imaterial inclui:', ['saberes, festas e tradições', 'somente prédios', 'apenas esculturas', 'recursos minerais'], 0)
    ]
};

module.exports = bancos;
